export const vendorData = [
    {
        id: 1,
        coverImg: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/cropped-bg_store2-300x144.jpg",
        avatar: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/store-2.jpg",
        name: "Library",
        quantity: 10,
        address: 'Đà Nẵng - Việt Nam',
        phone: "0365160470",
    },
    {
        id: 2,
        coverImg: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/cropped-bg_store2-300x144.jpg",
        avatar: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/store-2.jpg",
        name: "Library",
        quantity: 10,
        address: 'Đà Nẵng - Việt Nam',
        phone: "0365160470",
    },
    {
        id: 3,
        coverImg: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/cropped-bg_store2-300x144.jpg",
        avatar: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/store-2.jpg",
        name: "Library",
        quantity: 10,
        address: 'Đà Nẵng - Việt Nam',
        phone: "0365160470",
    },
    {
        id: 4,
        coverImg: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/cropped-bg_store2-300x144.jpg",
        avatar: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/store-2.jpg",
        name: "Library",
        quantity: 10,
        address: 'Đà Nẵng - Việt Nam',
        phone: "0365160470",
    },
    {
        id: 5,
        coverImg: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/cropped-bg_store2-300x144.jpg",
        avatar: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/store-2.jpg",
        name: "Library",
        quantity: 10,
        address: 'Đà Nẵng - Việt Nam',
        phone: "0365160470",
    },
    {
        id: 6,
        coverImg: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/cropped-bg_store2-300x144.jpg",
        avatar: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/store-2.jpg",
        name: "Library",
        quantity: 10,
        address: 'Đà Nẵng - Việt Nam',
        phone: "0365160470",
    },
    {
        id: 7,
        coverImg: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/cropped-bg_store2-300x144.jpg",
        avatar: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/store-2.jpg",
        name: "Library",
        quantity: 10,
        address: 'Đà Nẵng - Việt Nam',
        phone: "0365160470",
    },
    {
        id: 8,
        coverImg: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/cropped-bg_store2-300x144.jpg",
        avatar: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/store-2.jpg",
        name: "Library",
        quantity: 10,
        address: 'Đà Nẵng - Việt Nam',
        phone: "0365160470",
    },
    {
        id: 9,
        coverImg: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/cropped-bg_store2-300x144.jpg",
        avatar: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/store-2.jpg",
        name: "Library",
        quantity: 10,
        address: 'Đà Nẵng - Việt Nam',
        phone: "0365160470",
    },
    {
        id: 10,
        coverImg: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/cropped-bg_store2-300x144.jpg",
        avatar: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/store-2.jpg",
        name: "Library",
        quantity: 10,
        address: 'Đà Nẵng - Việt Nam',
        phone: "0365160470",
    },
    {
        id: 11,
        coverImg: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/cropped-bg_store2-300x144.jpg",
        avatar: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/store-2.jpg",
        name: "Library",
        quantity: 10,
        address: 'Đà Nẵng - Việt Nam',
        phone: "0365160470",
    },
    {
        id: 12,
        coverImg: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/cropped-bg_store2-300x144.jpg",
        avatar: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/store-2.jpg",
        name: "Library",
        quantity: 10,
        address: 'Đà Nẵng - Việt Nam',
        phone: "0365160470",
    },
    {
        id: 13,
        coverImg: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/cropped-bg_store2-300x144.jpg",
        avatar: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/store-2.jpg",
        name: "Library",
        quantity: 10,
        address: 'Đà Nẵng - Việt Nam',
        phone: "0365160470",
    },
    {
        id: 14,
        coverImg: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/cropped-bg_store2-300x144.jpg",
        avatar: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/store-2.jpg",
        name: "Library",
        quantity: 10,
        address: 'Đà Nẵng - Việt Nam',
        phone: "0365160470",
    },
    {
        id: 15,
        coverImg: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/cropped-bg_store2-300x144.jpg",
        avatar: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/store-2.jpg",
        name: "Library",
        quantity: 10,
        address: 'Đà Nẵng - Việt Nam',
        phone: "0365160470",
    },
    {
        id: 16,
        coverImg: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/cropped-bg_store2-300x144.jpg",
        avatar: "https://demo2.pavothemes.com/bookory/wp-content/uploads/2022/11/store-2.jpg",
        name: "Library",
        quantity: 10,
        address: 'Đà Nẵng - Việt Nam',
        phone: "0365160470",
    },
]